
vim.api.nvim_set_hl(0, "CursorLine",   { bg = "#282828", fg = "NONE", })
vim.api.nvim_set_hl(0, "VisualNOS",    { bg = "#444444", fg = "#000000", })
vim.api.nvim_set_hl(0, "Normal",       { bg = "#252525", fg = "#727272", })
vim.api.nvim_set_hl(0, "StatusLine",   { bg = "#3A3A3A", fg = "#AF87D7", })
vim.api.nvim_set_hl(0, "StatusLineNC", { bg = "#303030", fg = "#767676", })

vim.api.nvim_set_hl(0, "NonText",      { bg = "NONE", fg = "#323232", })
vim.api.nvim_set_hl(0, "VertSplit",    { bg = "NONE", fg = "#353535", })
vim.api.nvim_set_hl(0, "Warning",      { bg = "NONE", fg = "#D66F01", })
vim.api.nvim_set_hl(0, "ModeMsg",      { bg = "NONE", fg = "#767676", })
vim.api.nvim_set_hl(0, "Error",        { bg = "NONE", fg = "#C53B82", })
vim.api.nvim_set_hl(0, "Conceal",      { bg = "NONE", fg = "#626262", })
vim.api.nvim_set_hl(0, "PreProc",      { bg = "NONE", fg = "#767676", })
vim.api.nvim_set_hl(0, "SpecialKey",   { bg = "NONE", fg = "#6c5b9e", })
vim.api.nvim_set_hl(0, "FoldColumn",   { bg = "NONE", fg = "#666666", })
vim.api.nvim_set_hl(0, "WildMenu",     { bg = "NONE", fg = "#D75F5F", })
vim.api.nvim_set_hl(0, "ColorColumn",  { bg = "NONE", fg = "#000000", })
vim.api.nvim_set_hl(0, "SignColumn",   { bg = "NONE", fg = "#767676", })
vim.api.nvim_set_hl(0, "Cursor",       { bg = "NONE", fg = "#000000", })
vim.api.nvim_set_hl(0, "DiffAdd",      { bg = "NONE", fg = "#87AF87", })
vim.api.nvim_set_hl(0, "DiffChange",   { bg = "NONE", fg = "#008FBF", })
vim.api.nvim_set_hl(0, "DiffDelete",   { bg = "NONE", fg = "#AF5F87", })
vim.api.nvim_set_hl(0, "DiffText",     { bg = "NONE", fg = "#D7AF5F", })
vim.api.nvim_set_hl(0, "Operator",     { bg = "NONE", fg = "#555555", })
vim.api.nvim_set_hl(0, "Statement",    { bg = "NONE", fg = "#C53B82", })
vim.api.nvim_set_hl(0, "Special",      { bg = "NONE", fg = "#8567A3", })
vim.api.nvim_set_hl(0, "Identifier",   { bg = "NONE", fg = "#C53B82", })
vim.api.nvim_set_hl(0, "Constant",     { bg = "NONE", fg = "#C53B82", })
vim.api.nvim_set_hl(0, "Number",       { bg = "NONE", fg = "#afc460", })
vim.api.nvim_set_hl(0, "Boolean",      { bg = "NONE", fg = "#C53B82", })
vim.api.nvim_set_hl(0, "Keyword",      { bg = "NONE", fg = "#6A6A6A", })
vim.api.nvim_set_hl(0, "Function",     { bg = "NONE", fg = "#C53B82", })
vim.api.nvim_set_hl(0, "Delimiter",    { bg = "NONE", fg = "#8567A3", })
vim.api.nvim_set_hl(0, "Question",     { bg = "NONE", fg = "#BBE73D", })
vim.api.nvim_set_hl(0, "Conditonal",   { bg = "NONE", fg = "#D33FFF", })
vim.api.nvim_set_hl(0, "Label",        { bg = "NONE", fg = "#D0EE7A", })
vim.api.nvim_set_hl(0, "Character",    { bg = "NONE", fg = "#D33FFF", })
vim.api.nvim_set_hl(0, "Typedef",      { bg = "NONE", fg = "#000000", })
vim.api.nvim_set_hl(0, "SpecialChar",  { bg = "NONE", fg = "#333333", })
vim.api.nvim_set_hl(0, "Tag",          { bg = "NONE", fg = "#D33FFF", })
vim.api.nvim_set_hl(0, "Debug",        { bg = "NONE", fg = "#D33FFF", })
vim.api.nvim_set_hl(0, "ErrorMsg",     { bg = "NONE", fg = "#C53B82", })
vim.api.nvim_set_hl(0, "WarningMsg",   { bg = "NONE", fg = "#d1771b", })
vim.api.nvim_set_hl(0, "MoreMsg",      { bg = "NONE", fg = "#777777", })
vim.api.nvim_set_hl(0, "Ignore",       { bg = "NONE", fg = "#d1771b", })
vim.api.nvim_set_hl(0, "QuickFixLine", { bg = "NONE", fg = "#DE0000", })

vim.api.nvim_set_hl(0, "TabLine",      { bg = "NONE", fg = "#D33FFF", })
vim.api.nvim_set_hl(0, "TabLineFill",  { bg = "NONE", fg = "#D33FFF", })
vim.api.nvim_set_hl(0, "TabLineSel",   { bg = "NONE", fg = "#D33FFF", })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "NONE", fg = "#D33FFF", })
vim.api.nvim_set_hl(0, "SpellRare",    { bg = "NONE", fg = "#D33FFF", })
vim.api.nvim_set_hl(0, "htmlTag",      { bg = "NONE", fg = "#000000", })
vim.api.nvim_set_hl(0, "htmlEndTag",   { bg = "NONE", fg = "#000000", })

vim.api.nvim_set_hl(0, "diffAdded",    { bg = "NONE", fg = "#9EB73D", })
vim.api.nvim_set_hl(0, "diffRemoved",  { bg = "NONE", fg = "#C53B82", })

vim.api.nvim_set_hl(0, "StatusLineTerm",    { bg = "NONE", fg = "#D33FFF", })
vim.api.nvim_set_hl(0, "StatusLineTermNC",  { bg = "NONE", fg = "#D33FFF", })
vim.api.nvim_set_hl(0, "helpHyperTextJump", { bg = "NONE", fg = "#AF87D7", })

vim.api.nvim_set_hl(0, "SpecialComment", { bg = "NONE", fg = "#d1771b", })
vim.api.nvim_set_hl(0, "CursorLineFold", { bg = "#D33FFF", fg = "#000000", })

vim.api.nvim_set_hl(0, "Visual",       { bg = "#232323", fg = "NONE", bold = true })
vim.api.nvim_set_hl(0, "Search",       { bg = "NONE", fg = "#C53B82", bold = true })
vim.api.nvim_set_hl(0, "IncSearch",    { bg = "NONE", fg = "#C53B82", bold = true })
vim.api.nvim_set_hl(0, "MatchParen",   { bg = "NONE", fg = "#C53B82", bold = true })
vim.api.nvim_set_hl(0, "Directory",    { bg = "NONE", fg = "#AF87D7", bold = true })
vim.api.nvim_set_hl(0, "Title",        { bg = "NONE", fg = "#C53B82", bold = true })

vim.api.nvim_set_hl(0, "Type",         { bg = "NONE", fg = "#8567A3", italic = false })
vim.api.nvim_set_hl(0, "Comment",      { bg = "NONE", fg = "#525252", italic = false })
vim.api.nvim_set_hl(0, "Float",        { bg = "NONE", fg = "#afc460", italic = false })
vim.api.nvim_set_hl(0, "String",       { bg = "NONE", fg = "#8567A3", })
vim.api.nvim_set_hl(0, "Repeat",       { bg = "NONE", fg = "#8567A3", italic = false })
vim.api.nvim_set_hl(0, "Include",      { bg = "NONE", fg = "#BBE73D", italic = false })
vim.api.nvim_set_hl(0, "Define",       { bg = "NONE", fg = "#C53B82", italic = false })
vim.api.nvim_set_hl(0, "Structure",    { bg = "NONE", fg = "#BBE73D", italic = false })
vim.api.nvim_set_hl(0, "Macro",        { bg = "NONE", fg = "#BBE73D", italic = false })
vim.api.nvim_set_hl(0, "StorageClass", { bg = "NONE", fg = "#BBE73D", italic = false })

vim.api.nvim_set_hl(0, "LineNr",       { bg = "#252525", fg = "#6F6F6F", italic = true })
vim.api.nvim_set_hl(0, "Folded",       { bg = "#232323", fg = "#494949", })
vim.api.nvim_set_hl(0, "CursorLineNr", { bg = "#282828", fg = "#6c5b9e", italic = true })

vim.api.nvim_set_hl(0, "Underlined",   { bg = "NONE", fg = "#6C5B9E", underline = true })
vim.api.nvim_set_hl(0, "SpellBad",     { bg = "NONE", fg = "#AF5F87", underline = true })
vim.api.nvim_set_hl(0, "SpellCap",     { bg = "NONE", fg = "#87AF87", underline = true })
vim.api.nvim_set_hl(0, "SpellLocal",   { bg = "NONE", fg = "#D7AF5F", underline = true })

vim.api.nvim_set_hl(0, "Exception",    { bg = "NONE", fg = "#BBE73D", italic = false, bold = true })
vim.api.nvim_set_hl(0, "Todo",         { bg = "NONE", fg = "#D66F01", italic = false, bold = true })

vim.api.nvim_set_hl(0, "Pmenu",        { bg = "#292929", fg = "#686868", })
vim.api.nvim_set_hl(0, "PmenuSel",     { bg = "#2f2f2f", fg = "NONE", bold = true })

vim.api.nvim_set_hl(0, "PmenuSbar",    { bg = "#313131", fg = "#000000", })
vim.api.nvim_set_hl(0, "PmenuThumb",   { bg = "#434343", fg = "#000000", })

vim.api.nvim_set_hl(0, "CursorLine",   { bg = "#282828", fg = "NONE", })


vim.api.nvim_set_hl(0, "HlSearchNear", { bg = "NONE", fg = "#C53B82" })
vim.api.nvim_set_hl(0, "HlSearchLens", { bg = "NONE", fg = "#444444" })
vim.api.nvim_set_hl(0, "HlSearchLensNear", { bg = "NONE", fg = "#a8bc5c" })
vim.api.nvim_set_hl(0, "HlSearchFloat", { bg = "NONE", fg = "#000000" })

vim.api.nvim_set_hl(0, "lsoutlinefile",          { bg = "none", fg = "#af87d7" })
vim.api.nvim_set_hl(0, "lsoutlinemodule",        { bg = "none", fg = "#666666" })
vim.api.nvim_set_hl(0, "lsoutlinenamespace",     { bg = "none", fg = "#666666" })
vim.api.nvim_set_hl(0, "lsoutlinepackage",       { bg = "none", fg = "#666666" })
vim.api.nvim_set_hl(0, "lsoutlineclass",         { bg = "none", fg = "#bbe73d", bold = true, italic = false })
vim.api.nvim_set_hl(0, "lsoutlinemethod",        { bg = "none", fg = "#c53b82", italic = false })
vim.api.nvim_set_hl(0, "lsoutlineproperty",      { bg = "none", fg = "#6a5a9d" })
vim.api.nvim_set_hl(0, "lsoutlinefield",         { bg = "none", fg = "#666666" })
vim.api.nvim_set_hl(0, "lsoutlineconstructor",   { bg = "none", fg = "#666666" })
vim.api.nvim_set_hl(0, "lsoutlineenum",          { bg = "none", fg = "#666666" })
vim.api.nvim_set_hl(0, "lsoutlineinterface",     { bg = "none", fg = "#666666" })
vim.api.nvim_set_hl(0, "lsoutlinefunction",      { bg = "none", fg = "#c53b82", italic = false })
vim.api.nvim_set_hl(0, "lsoutlinevariable",      { bg = "none", fg = "#696969" })
vim.api.nvim_set_hl(0, "lsoutlineconstant",      { bg = "none", fg = "#614f97" })
vim.api.nvim_set_hl(0, "lsoutlinestring",        { bg = "none", fg = "#444444" })
vim.api.nvim_set_hl(0, "lsoutlinenumber",        { bg = "none", fg = "#afc460" })
vim.api.nvim_set_hl(0, "lsoutlineboolean",       { bg = "none", fg = "#c53b82" })
vim.api.nvim_set_hl(0, "lsoutlinearray",         { bg = "none", fg = "#614f97" })
vim.api.nvim_set_hl(0, "lsoutlineobject",        { bg = "none", fg = "#666666" })
vim.api.nvim_set_hl(0, "lsoutlinekey",           { bg = "none", fg = "#666666" })
vim.api.nvim_set_hl(0, "lsoutlinenull",          { bg = "none", fg = "#c53b82" })
vim.api.nvim_set_hl(0, "lsoutlineenummember",    { bg = "none", fg = "#666666" })
vim.api.nvim_set_hl(0, "lsoutlinestruct",        { bg = "none", fg = "#666666" })
vim.api.nvim_set_hl(0, "lsoutlineevent",         { bg = "none", fg = "#666666" })
vim.api.nvim_set_hl(0, "lsoutlineoperator",      { bg = "none", fg = "#666666" })
vim.api.nvim_set_hl(0, "lsoutlinetypeparameter", { bg = "none", fg = "#666666" })
vim.api.nvim_set_hl(0, "lsoutlinetypealias",     { bg = "none", fg = "#666666" })
vim.api.nvim_set_hl(0, "lsoutlineparameter",     { bg = "none", fg = "#8567a3" })
vim.api.nvim_set_hl(0, "lsoutlinestaticmethod",  { bg = "none", fg = "#666666" })
vim.api.nvim_set_hl(0, "lsoutlinemacro",         { bg = "none", fg = "#666666" })
